// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfkgz0G_xev4bPih1FJ3ooToXUd0GrUvQ',
    appId: '1:82699656236:web:11ce82fa1ce85123fc8589',
    messagingSenderId: '82699656236',
    projectId: 'wechat-5ce2e',
    authDomain: 'wechat-5ce2e.firebaseapp.com',
    storageBucket: 'wechat-5ce2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsB-g7_ExYKBIOjJK1007mqTbgkYdWtME',
    appId: '1:82699656236:android:f89189a00074e59afc8589',
    messagingSenderId: '82699656236',
    projectId: 'wechat-5ce2e',
    storageBucket: 'wechat-5ce2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlyXw1pXmvhN2_Hra6tDTLlQL4kbW8vbY',
    appId: '1:82699656236:ios:efdd560d483890cffc8589',
    messagingSenderId: '82699656236',
    projectId: 'wechat-5ce2e',
    storageBucket: 'wechat-5ce2e.appspot.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlyXw1pXmvhN2_Hra6tDTLlQL4kbW8vbY',
    appId: '1:82699656236:ios:efdd560d483890cffc8589',
    messagingSenderId: '82699656236',
    projectId: 'wechat-5ce2e',
    storageBucket: 'wechat-5ce2e.appspot.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfkgz0G_xev4bPih1FJ3ooToXUd0GrUvQ',
    appId: '1:82699656236:web:6d24195a3d19513cfc8589',
    messagingSenderId: '82699656236',
    projectId: 'wechat-5ce2e',
    authDomain: 'wechat-5ce2e.firebaseapp.com',
    storageBucket: 'wechat-5ce2e.appspot.com',
  );
}
